#!/bin/bash
#
# Arch Base Installation Framework (version 2.2 - 23-Mar-2016)
#
# Written by Carl Duff for PacBang Linux
#
# This program is free software, provided under the GNU General Public License
# as published by the Free Software Foundation. So feel free to copy, distribute,
# or modify it as you wish.
#

ABSOLUT_FILENAME=`readlink -e "$0"`
filesdir=`dirname "$ABSOLUT_FILENAME"`

source "./modules/installer-variables.sh"                  # list of variables
source "./modules/core-functions.sh"                       # language, checks
source "./modules/configuration-functions.sh"              # Keyboard, locale, time zone, FSTAB, mkinitcpio, user controls
source "./modules/system-partitioning.sh"                  # managing partitions, installing the boot
source "./modules/luks.sh"                                 # Encryption
source "./modules/lvm.sh"                                  # LVM control
source "./modules/installation-functions.sh"               # system installation functions
source "./modules/swappiness-config.sh"                    # SWAPPINESS
source "./modules/devices-config.sh"                       # tune2fs
source "./modules/shell_installer.sh"                      # SHELL installer functions
source "./modules/main-interfaces.sh"                      # main menu interface


######################################################################
##                                                                  ##
##                        Execution                                 ##
##                                                                  ##
######################################################################

id_system
select_language
check_requirements

    while true; do
          main_menu      
    done
