#!/bin/bash
#
# Arch Base Installation Framework (version 2.2 - 23-Mar-2016)
#
# Written by Carl Duff for PacBang Linux
#
# This program is free software, provided under the GNU General Public License
# as published by the Free Software Foundation. So feel free to copy, distribute,
# or modify it as you wish.
#

ABSOLUT_FILENAME=$(readlink -e "$0")
filesdir=$(dirname "$ABSOLUT_FILENAME")

set -o pipefail ;

for i in "$filesdir"/modules/*.sh; do source "$i"; done ;
#_src_fls=$(find "$filesdir/modules" -maxdepth 1 -type f -iname "*.sh")
#for i in ${_src_fls[*]}; do
#    source "$i"
#done
#unset _src_fls


######################################################################
##                                                                  ##
##                        Execution                                 ##
##                                                                  ##
######################################################################

setcolor
while [ -n "$1" ]; do
	case "$1" in
		-cli) _type_setup=0
			;;
		-gui) _type_setup=1
			;;
		-[h?] | --help) _help
						wait
						exit 0
						;;
		*) $SETCOLOR_ERROR
			echo -e -n "\nUnkonwn parameter\n"
			$SETCOLOR_NORMAL
			_help
			wait
			exit 1
			;;
	esac
	shift
done
us_dlgrc_conf
id_system
select_language
check_requirements

    while true; do
          main_menu      
    done
